### ISSUE TITLE
What is the _ argument in BYTETracker update?

### ISSUE THREAD

**Issue by n3ry7** [kadirnar/bytetrack-pip#1]
What is the purpose of the _ argument in the update method?

https://github.com/kadirnar/bytetrack-pip/blob/eda64c49f8d9fca66d78fdc5cf21f492a6c84fcc/bytetracker/byte_tracker.py#L162

**Comment by kadirnar** [comment]
Hello @n3ry7 ,

Thank you for your interest. Not important. I added 2 parameters for [TrackerHub](https://github.com/kadirnar/TrackerHub/) library. Other tracker algorithm([strongsort-pip](https://github.com/kadirnar/strongsort-pip/blob/main/strongsort/strong_sort.py#L32)) require 2 parameters.

**Comment by n3ry7** [comment]
Thanks!
