### ISSUE TITLE
ModuleNotFoundError: No module named 'yolov5'

### ISSUE THREAD

**Issue by SkalskiP** [kadirnar/bytetrack-pip#3]
# Reproduction path

1. Install `bytetracker`

```bash
pip install bytetracker
```

2. Import `bytetracker`

```python
import bytetracker
```

# Stacktrace

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-447665eda60c>](https://localhost:8080/#) in <module>
      5 display.clear_output()
      6 
----> 7 import bytetracker
      8 print("bytetracker.__version__:", bytetracker.__version__)

1 frames
[/usr/local/lib/python3.9/dist-packages/bytetracker/byte_tracker.py](https://localhost:8080/#) in <module>
      1 import numpy as np
----> 2 from yolov5.utils.general import xywh2xyxy, xyxy2xywh
      3 
      4 from bytetracker import matching
      5 from bytetracker.basetrack import BaseTrack, TrackState

ModuleNotFoundError: No module named 'yolov5'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

It looks like you use yolov5 in your code, but it is not part of the dependencies.

**Comment by kadirnar** [comment]
Thank you for the feedback. I will delete the yolov5 library in this library. I will write and update the functions.

**Comment by SkalskiP** [comment]
It would be awesome, as I wanted to use that lib in one of our tutorials.

**Comment by kadirnar** [comment]
Can you check?

I'm sorry for the late reply. Now I am doing projects on generative models.

**Comment by SimonCL17** [comment]
Hi there, I am new to ByteTrack but I am looking at using YoloV5 as the detector. Is there a way for me to get an older version of the repo that included the YoloV5 library? Thanks

**Comment by kadirnar** [comment]
> Hi there, I am new to ByteTrack but I am looking at using YoloV5 as the detector. Is there a way for me to get an older version of the repo that included the YoloV5 library? Thanks

Why do you want the old version? Which version are you using? Are you using yolov5-pip?
