### ISSUE TITLE
What is dets?

### ISSUE THREAD

**Issue by Tlaloc-Es** [kadirnar/bytetrack-pip#6]
Hello I am using YoloV7 and I get a predictions object like this

`['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slotnames__', '__str__', '__subclasshook__', '__weakref__', 'display', 'files', 'imgs', 'n', 'names', 'pandas', 'pred', 'print', 'render', 's', 'save', 'show', 't', 'tolist', 'xywh', 'xywhn', 'xyxy', 'xyxyn']`

I tried call update(predictions, None) with almost all options and always I get an error like

TypeError: list indices must be integers or slices, not tuple

I tried call directly

`BYTETracker().update([1,1,1,1,1], None)` and `BYTETracker().update((1,1,1,1,1), None)`, but I got the same error,

So how can I call the update(), it is necessary set always None to _ parameter?

Thanks.

**Comment by icesohelrana** [comment]
Using BYTETracker().update(torch.tensor([[1,1,1,1,1]]), None) will work
